[book]
authors = ["Chun Liu"]
language = "en"
multilingual = false
src = "src"
title = "Azure Scrolls"
description = "Azure related posts"

[output.html]
git-repository-url = "https://github.com/chunliu/my-docs"
no-section-label = true
default-theme = "Ayu"

[output.html.fold]
enable = true
level = 0